const FONT_OPENSANS_BOLD = 'OpenSans-Bold';
const FONT_OPENSANS_BOLDITALIC = 'OpenSans-BoldItalic';
const FONT_OPENSANS_EXTRABOLD = 'OpenSans-ExtraBold';
const FONT_OPENSANS_EXTRABOLDITALIC = 'OpenSans-ExtraBoldItalic';
const FONT_OPENSANS_ITALIC = 'OpenSans-Italic';
const FONT_OPENSANS_LIGHT = 'OpenSans-Light';
const FONT_OPENSANS_LIGHTITALIC = 'OpenSans-LightItalic';
const FONT_OPENSANS_MEDIUM = 'OpenSans-Medium';
const FONT_OPENSANS_MEDIUMITALIC = 'OpenSans-MediumItalic';
const FONT_OPENSANS_REGULAR = 'OpenSans-Regular';

export const fontFamily = {
    FONT_OPENSANS_BOLD,
    FONT_OPENSANS_BOLDITALIC,
    FONT_OPENSANS_EXTRABOLD,
    FONT_OPENSANS_EXTRABOLDITALIC,
    FONT_OPENSANS_ITALIC,
    FONT_OPENSANS_LIGHT,
    FONT_OPENSANS_LIGHTITALIC,
    FONT_OPENSANS_MEDIUM,
    FONT_OPENSANS_MEDIUMITALIC,
    FONT_OPENSANS_REGULAR
}