// ----------------------------------------------- KEY STORAGE

// KEY USER, LOGIN
export const ACCESS_TOKEN = 'ACCESS_TOKEN';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const IS_LOGIN = 'IS_LOGIN';

// KEY PERMISSION LOCATION
export const PERMISSIONS_LOCATION_APP = 'PERMISSIONS_LOCATION_APP';
export const PERMISSIONS_ANDROID_ACCESS_FINE_LOCATION =
  'PERMISSIONS_ANDROID_ACCESS_FINE_LOCATION';
export const PERMISSIONS_ANDROID_ACCESS_BACKGROUND_LOCATION =
  'PERMISSIONS_ANDROID_ACCESS_BACKGROUND_LOCATION';
export const PERMISSIONS_IOS_LOCATION_ALWAYS =
  'PERMISSIONS_IOS_LOCATION_ALWAYS';
export const PERMISSIONS_IOS_LOCATION_WHEN_IN_USE =
  'PERMISSIONS_IOS_LOCATION_WHEN_IN_USE';

// KEY CART
export const STORAGE_CART = 'STORAGE_CART';
