const ACTION_REQUEST_OTP = 'ACTION_REQUEST_OTP';
const ACTION_SEND_OTP = 'ACTION_SEND_OTP';
const ACTION_LOGIN_BYPHONE = 'ACTION_LOGIN_BYPHONE';
const ACTION_LOGIN_BYPHONE_SUCCESS = 'ACTION_LOGIN_BYPHONE_SUCCESS';
const ACTION_LOGIN_BYPHONE_FAIL = 'ACTION_LOGIN_BYPHONE_FAIL';
export const typeUserAction = {
  ACTION_REQUEST_OTP,
  ACTION_SEND_OTP,
  ACTION_LOGIN_BYPHONE,
  ACTION_LOGIN_BYPHONE_SUCCESS,
  ACTION_LOGIN_BYPHONE_FAIL,
};
