const ACTION_SELECT_TOPPING = 'ACTION_SELECT_TOPPING';
const ACTION_SELECT_OPTION_BUY = 'ACTION_SELECT_OPTION_BUY';
const ACTION_GET_OPTION_BUY_PRODUCT = 'ACTION_GET_OPTION_BUY_PRODUCT';
const ACTION_SET_OPTION_BUY_PRODUCT = 'ACTION_SET_OPTION_BUY_PRODUCT';
const ACTION_SET_CART = 'ACTION_SET_CART';
export const typeCartACtion = {
  ACTION_GET_OPTION_BUY_PRODUCT,
  ACTION_SET_OPTION_BUY_PRODUCT,
  ACTION_SELECT_TOPPING,
  ACTION_SELECT_OPTION_BUY,
  ACTION_SET_CART,
};
