const ACTION_GET_CATEGORY = 'ACTION_GET_CATEGORY';
const ACTION_SET_POSITION_CATEGORY = 'ACTION_SET_POSITION_CATEGORY';

export const typeCategoryAction = {
  ACTION_GET_CATEGORY,
  ACTION_SET_POSITION_CATEGORY,
};
